# Generated by Django 5.0.6 on 2024-07-01 03:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('nombreCategoria', models.CharField(max_length=40, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Empresa')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('logo', models.ImageField(null=True, upload_to='imagenes', verbose_name='Logo')),
                ('cantVehiculos', models.IntegerField(null=True, verbose_name='Cantidad de Vehículos')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Vehículo')),
                ('patente', models.CharField(default='ABCD00', max_length=6, unique=True, verbose_name='Patente Vehículo')),
                ('cantPasajeros', models.IntegerField(verbose_name='Capacidad del Vehículo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca Vehículo')),
                ('precioPorPersona', models.IntegerField(verbose_name='Valor por Persona')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriavehiculo', verbose_name='Id Categoría')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core.empresa', verbose_name='Id Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Reserva')),
                ('total', models.BigIntegerField(verbose_name='Total')),
                ('fechaReserva', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Reserva')),
                ('estado', models.CharField(default='Vehículo Reservado', max_length=50, verbose_name='Estado')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.empresa', verbose_name='Id Empresa')),
                ('idVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.vehiculo', verbose_name='Id Vehículo')),
            ],
        ),
    ]
