# Generated by Django 5.0.6 on 2024-07-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cantVehiculos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cantAutos',
            field=models.IntegerField(null=True, verbose_name='Cantidad de Automoviles'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cantBuses',
            field=models.IntegerField(null=True, verbose_name='Cantidad de Buses'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cantVan',
            field=models.IntegerField(null=True, verbose_name='Cantidad de Vans'),
        ),
        migrations.AlterField(
            model_name='categoriavehiculo',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoría'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='idEmpresa',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Empresa'),
        ),
    ]
