# Generated by Django 5.0.6 on 2024-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_empresa_cantvehiculos_empresa_cantautos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vehiculos/', verbose_name='Imagen'),
        ),
    ]
