# Generated by Django 5.0.6 on 2024-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(default='Apellido por defecto', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidadPasajero',
            field=models.IntegerField(default=1, verbose_name='Cantidad de pasajero'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='destino',
            field=models.CharField(default='destino por defecto', max_length=60, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='nombre por defecto', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pasaporteCliente',
            field=models.CharField(default=1, max_length=50, verbose_name='Pasaporte Cliente'),
        ),
    ]
