# Generated by Django 5.0.6 on 2024-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_apellido_reserva_cantidadpasajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad Transfer'),
        ),
    ]
