# Generated by Django 5.0.6 on 2024-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehiculo_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('nombre', models.CharField(default='nombre por defecto', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(default='Apellido por defecto', max_length=50, verbose_name='Apellido')),
                ('pasaporteCliente', models.CharField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='Pasaporte Cliente')),
                ('cantidadPasajero', models.IntegerField(default=1, verbose_name='Cantidad de pasajero')),
                ('destino', models.CharField(default='destino por defecto', max_length=60, verbose_name='Destino')),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidadPasajero',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pasaporteCliente',
        ),
    ]
