# Generated by Django 5.0.6 on 2024-07-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detallereserva_remove_reserva_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='disponibilidad',
            field=models.BooleanField(default=True, max_length=10, verbose_name='Disponibilidad Transfer'),
        ),
    ]
